spring:
  application:
    name: FintechService

app:
  version: 0.0.1

dataSource:
  type: FOLDER
  path: C:/Rock/Datas/Calypso/Persistence/dataCenter

logging:
  config: classpath:fintech/logback.xml
  controller:
    exception:
      printStack: true

configs:
  taskConfigFolder: task

persistent:
  type: FILE
  folder: /calypso/Calypso

event:
  generate: true
  folder: event/#yyyyMM#

local:
  file:
    root: C:/Rock/Datas/Calypso/Persistence/dataCenter

application:
  calypso:
    serviceUrl: http://127.0.0.1
    instanceList: 87v17;30087,129v17;30129
    serviceName: services