spring:
  application:
    name: FintechService

app:
  version: 0.0.1

dataSource:
  type: FOLDER
  path: C:/Rock/Datas/Calypso/Persistence/dataCenter

logging:
  config: classpath:fintech/logback.xml
  controller:
    exception:
      printStack: true

configs:
  taskConfigFolder: task

persistent:
  type: FILE
  folder: /calypso/Calypso

event:
  generate: true
  folder: event/#yyyyMM#

local:
  file:
    root: C:/Rock/Datas/Calypso/Persistence/dataCenter

application:
  calypso:
    serviceUrl: http://127.0.0.1
    instanceList: 87v17;30087,129v17;30129,v17prod;30013
    serviceName: services

ftpSourceList:

  - id: cal129_calypso
    type: FTP
    server: 168.64.37.129
    port: 21
    user: calypso
    pwd: App@Admin123

  - id: traiana_uat
    type: SFTP
    server: 199.201.113.151
    port: 22
    user: arch.tst.huatai
    pwd: MpfmgnQxss3u

remoteSource:
  ftpFolderList:

    - id: cal129_scb_out
      sourceId: cal129_calypso
      folder: /opt/calypso/report/SCB

    - id: cal129_scb_ack_result
      sourceId: cal129_calypso
      folder: /opt/calypso/report/SCB/result

    - id: traiana_income
      sourceId: traiana_uat
      folder: /Incoming

    - id: traiana_ack_result
      sourceId: traiana_uat
      folder: /Outgoing

ftpSyncList:

  - source: cal129_scb_out
    dest: traiana_income
    backup: /opt/calypso/report/SCB/backup

  - source: traiana_ack_result
    dest: cal129_scb_ack_result
    sendEmail: true
    subject: Traiana_SCB_PB(UAT)_GIVE_UP_TRADE
    emailReceiveList:
      - group1
      - group3
    emailCCList:
      - group2

emailList:
  - name: group1
    list: rockchen@htsc.com
  - name: group2
    list: ansonman@htsc.com, sunzhennan@kmerit.com
  - name: group3
    list: kennethhan@htsc.com, chesterchan@htsc.com
  - name: group4
    list: fatlon@sina.cn