#Rock Local Service, connect to ROCK_DEV env
server:
  port: ${SERVER_PORT:20001}

persistent:
  type: FILE
  folder: C:/Rock/Datas/Calypso/Persistence

local:
  file:
    root: C:/Rock/Datas/Calypso/Persistence/dataCenter

application:
  calypso:
    instanceList:
      - name: 87v17
        url: http://127.0.0.1:30087/services/
      - name: 129v17
        url: http://127.0.0.1:30129/services/